name: Deploy to Yandex Cloud Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установка Yandex CLI
      - name: Install Yandex Cloud CLI
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH

      # Шаг 3: Аутентификация в Yandex Cloud
      - name: Authenticate in Yandex Cloud
        env:
          YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${YC_SERVICE_ACCOUNT_KEY}" > yc-sa-key.json
          yc config set service-account-key yc-sa-key.json
          yc config set cloud-id b1gvqb4s3f495f55ih0b
          yc config set folder-id b1glq93bir0j2f0sl892

      # Шаг 4: Установка kubectl
      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      # Шаг 5: Настройка подключения к Kubernetes
      - name: Configure kubectl
        env:
          YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        run: |
          KUBERNETES_CLUSTER_ID=catd750jtmg8as6vcm31
          yc managed-kubernetes cluster get-credentials --id $KUBERNETES_CLUSTER_ID --external
          kubectl get nodes

      # Шаг 6: Деплой приложения
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
